title: Alex Brohammer
permalink: ':title/'
url: "https://brohammer.github.io"

# Author Settings
author: Alex Brohammer
github: brohammer
linkedin: alex-brohammer

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 8
paginate_path: "blog/page/:num"

sass:
  sass_dir: assets/css/scss


collections:
  mashups:
    output: true
  videos:
    output: true

sass:
    sass_dir: assets/css/scss

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
